/**
 * API Client for Todo
 * Auto-generated by offbyte
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

/**
 * Get all todos
 */
export const getAllTodos = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = `${import.meta.env.VITE_API_URL}/api/todos${query ? '?' + query : ''}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch todos`);
  }

  return response.json();
};

/**
 * Get single todo by ID
 */
export const getTodoById = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/todos/${id}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch todo`);
  }

  return response.json();
};

/**
 * Create new todo
 */
export const createTodo = async (data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/todos`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to create todo`);
  }

  return response.json();
};

/**
 * Update todo (partial update)
 */
export const updateTodo = async (id, data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/todos/${id}`;
  
  const response = await fetch(url, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to update todo`);
  }

  return response.json();
};

/**
 * Delete todo
 */
export const deleteTodo = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/todos/${id}`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to delete todo`);
  }

  return response.json();
};

export default {
  getAllTodos,
  getTodoById,
  createTodo,
  updateTodo,
  deleteTodo
};
